# docker-compose.production.yml

volumes:
  pg_data_production:
  static_volume:
networks:
  default:
    name: taski_network
# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    networks:
      - default
  backend:
    image: xwavex2000/taski_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/backend_static
    networks:
      - default
    command: "gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"
  frontend:
    image: xwavex2000/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    networks:
      - default
  gateway:
    image: xwavex2000/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    networks:
      - default
    ports:
      - 8000:80